ubuntu/yaru_icons.dart

CHANGELOG.md
pubspec.yaml

Release 0.0.2

---

build-icons.sh
doc/icon_list.md

Library overview

---

README.md
build-icons.sh

Replace `fantasticon-flutter` with `icon-font-generator`.

Deprecate fantasticon-flutter

---

example/analysis_options.yaml
example/lib/main.dart
example/lib/src/animated_icons_grid.dart
example/lib/src/icon_size_provider.dart
example/lib/src/icons_grid.dart
example/lib/src/yaru_icon_data.dart
example/pubspec.yaml
lib/src/animations/yaru_animated_ok_icon.dart
lib/yaru_icons.dart
pubspec.yaml

[Capture vidéo du 03-09-2022 13:07:24.webm](https://user-images.githubusercontent.com/36476595/188267666-e2707096-acb7-4c5f-809f-8206843c624c.webm)
Related to https://github.com/ubuntu/yaru_widgets.dart/pull/197

Import animated icons from yaru_widgets.dart

---

example/lib/src/animated_icons_grid.dart
lib/src/animations/yaru_animated_no_network_icon.dart
lib/yaru_icons.dart

[Capture vidéo du 04-09-2022 18:46:52.webm](https://user-images.githubusercontent.com/36476595/188325385-5b18f5d1-e119-4bc6-ac9f-d947f809090b.webm)

Add YaruAnimatedNoNetworkIcon to animated icons

---

lib/src/animations/yaru_animated_ok_icon.dart

- late final class vars ;
- remove useless type definition ;
- better animation.
**Before:**
[Capture vidéo du 04-09-2022 20:38:09.webm](https://user-images.githubusercontent.com/36476595/188328570-afbdee0e-8768-4a94-8da4-d012c55efe87.webm)
**After:**
[Capture vidéo du 04-09-2022 20:31:17.webm](https://user-images.githubusercontent.com/36476595/188328573-efb4d7be-7b0c-409e-8f13-0ef082ccc3e3.webm)
**Note:** slowed down animation to clearly see the diff between them.

Yaru animated ok icon improvements

---

lib/src/animated_icons/yaru_animated_no_network_icon.dart
lib/src/animated_icons/yaru_animated_ok_icon.dart

Allow animated icons to be controlled by a custom animation controller.
No design change.
Fixes #83

Extract animationController from animated icons

---

CHANGELOG.md
pubspec.yaml

@Feichtmeier I release a major version because I didn't a lot and a lot of breaking change, I think this package is in it's definitive shape (I corrected all the icon names to be descriptively simple) 🙂

Release version 1.0.0

---

example/lib/src/example.dart
example/lib/src/icon_items.dart
example/lib/src/provider/search_provider.dart
lib/src/widgets/yaru_placeholder_icon.dart
lib/yaru_icons.dart

| Light | Dark |
| --- | --- |
| ![Capture d’écran du 2023-01-21 21-05-07](https://user-images.githubusercontent.com/36476595/213885961-d0511a52-8ae9-4b6c-8a7e-d8452a7e1541.png) | ![Capture d’écran du 2023-01-21 21-04-59](https://user-images.githubusercontent.com/36476595/213885965-a3c7cced-1d39-4dac-a3b5-03531ca62977.png) |
**Note:** I really need to clean up the example app.
CC @Zoospora @anasereijo
Fixes #118

Create placeholder icon

---

CHANGELOG.md
pubspec.yaml

I have escrowed the merging of the both currently pending PRs in the changelog.

Release version 1.0.2

---

example/lib/src/common/icon_dialog.dart
example/lib/src/common/icon_usage.dart
example/lib/src/common/search_entry.dart
example/lib/src/example.dart
example/linux/flutter/generated_plugin_registrant.cc
example/linux/flutter/generated_plugins.cmake
example/pubspec.yaml

- update yaru dependencies ;
- fix flutter depreciations.

Example: update deps

---

example/lib/src/icon_items.dart
lib/src/animated_icons/yaru_animated_compass_icon.dart
lib/yaru_icons.dart

[Capture vidéo du 2023-02-19 15-15-21.webm](https://user-images.githubusercontent.com/36476595/219955202-2613a1f2-b67f-44d8-a239-147bf828e54f.webm)
[Capture vidéo du 2023-02-19 15-39-03.webm](https://user-images.githubusercontent.com/36476595/219955201-3776a226-8ed5-4f82-9602-e3b2bc2a1c97.webm)
**In slow motion (in JIT mode so a bit laggy):**
[Capture vidéo du 2023-02-19 15-42-49.webm](https://user-images.githubusercontent.com/36476595/219955329-8237dd29-1fe2-4aa0-89d9-49e68b566b1d.webm)
CC @madsrh @anasereijo

Add animated compass icon

---

example/linux/flutter/generated_plugin_registrant.cc
example/linux/flutter/generated_plugins.cmake

Commit generated_plugins

---

lib/src/animated_icons/yaru_animated_no_network_icon.dart
lib/src/animated_icons/yaru_animated_ok_icon.dart

| Before | After 
| --- | ---
| ![Capture d’écran du 2023-02-24 14-23-05](https://user-images.githubusercontent.com/36476595/221189341-e7ff6b33-6233-463c-a74c-92556a6b3ac3.png) | ![Capture d’écran du 2023-02-24 14-23-28](https://user-images.githubusercontent.com/36476595/221189331-bbeb308a-23f6-4739-8866-48319f06fd83.png)
| Before | After 
| --- | ---
| ![Capture d’écran du 2023-02-24 14-11-57](https://user-images.githubusercontent.com/36476595/221189750-5f3b69c6-b1ad-4416-b7f0-dc87b1358f95.png) | ![Capture d’écran du 2023-02-24 14-12-25](https://user-images.githubusercontent.com/36476595/221189747-b8f667d0-7481-47cf-ba93-ab8258fdd8fa.png)
Fixes #132

Canvas masking issue on web platform

---

lib/src/animated_icons/yaru_animated_no_network_icon.dart
lib/src/animated_icons/yaru_animated_ok_icon.dart

No design change.
This widget is useless here, and moreover it affects performances (not noticeable here).

Remove useless ClipRect

---

.github/workflows/pr.yaml
.github/workflows/release.yml

https://github.com/googleapis/release-please

chore: release-please

---

.github/workflows/pr.yaml
.github/workflows/release.yml

https://github.com/ubuntu-flutter-community/actions

ci: reuse pr title & release actions from ufc/actions

---

example/lib/src/icon_items.dart
lib/src/animated_icons/yaru_animated_heart_icon.dart
lib/yaru_icons.dart

[Capture vidéo du 2023-07-03 00-44-33.webm](https://github.com/ubuntu/yaru_icons.dart/assets/36476595/d1fe0826-9fc4-4dc3-bf42-d00277d19650)

feat: add animated heart icon

---

lib/src/animated_icons/yaru_animated_compass_icon.dart
lib/src/animated_icons/yaru_animated_heart_icon.dart
lib/src/animated_icons/yaru_animated_icon.dart
lib/src/animated_icons/yaru_animated_no_network_icon.dart
lib/src/animated_icons/yaru_animated_ok_icon.dart

Cleanup animated icons API and comments.

refactor!: cleanup animated icons API and comments

---

lib/src/animated_icons/yaru_animated_icon.dart

Use a late animation controller instead of the nullable one.

refactor: use a late animation controller

---

example/lib/src/icon_items.dart
lib/src/widgets/animated_icons/yaru_animated_heart_icon.dart
lib/src/widgets/animated_icons/yaru_animated_star_icon.dart
lib/src/widgets/animated_icons/yaru_single_path_trace_painter.dart
lib/yaru_icons.dart

[Capture vidéo du 2023-07-29 14-15-19.webm](https://github.com/ubuntu/yaru_icons.dart/assets/36476595/9a04b0d5-a62f-4dfa-a2ff-b07c3cb0db09)
Fixes #138

feat: add animated star icon

---

lib/src/widgets/animated_icons/yaru_animated_icon.dart

Add `YaruAnimatedIcon` `initialProgress` property.

feat: add YaruAnimatedIcon initialProgress property

---

example/pubspec.yaml

chore: update example app yaru package versions

---

.github/workflows/publish.yml

This should fix this problem: https://github.com/ubuntu/yaru_icons.dart/actions/runs/6459650757/job/17535854563

chore: fix github pages flutter version
